# Generated by Django 5.2 on 2025-04-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckPrev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('composition', models.CharField(max_length=255)),
                ('is_change_down_flag', models.CharField(choices=[('down', 'Down'), ('up', 'Up'), ('nothing', 'Nothing')], default='nothing', max_length=255)),
                ('rows', models.IntegerField()),
                ('cols', models.IntegerField()),
            ],
        ),
    ]
