# Generated by Django 5.2 on 2025-04-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkprev',
            name='phase',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkprev',
            name='start_phase',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
