# Generated by Django 5.2 on 2025-04-17 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_checkprev_start_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Famili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rows', models.IntegerField()),
                ('cols', models.IntegerField()),
                ('check_prev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.famili')),
            ],
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_change_down_flag', models.CharField(choices=[('down', 'Down'), ('up', 'Up'), ('nothing', 'Nothing')], default='nothing', max_length=255)),
                ('phase', models.CharField(max_length=255)),
                ('check_prev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
        ),
    ]
