# Generated by Django 5.2 on 2025-04-18 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_famili_product_composition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckPrev',
        ),
    ]
