# Generated by Django 5.2 on 2025-04-18 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_delete_checkprev'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_none', models.ImageField(upload_to='product_media/')),
                ('image_true', models.ImageField(upload_to='product_media/')),
                ('image_false', models.ImageField(upload_to='product_media/')),
                ('image_other', models.ImageField(upload_to='product_media/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
        ),
    ]
