# Generated by Django 5.2 on 2025-04-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_productmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='img_width',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
