# Generated by Django 5.2 on 2025-05-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_product_img_height_product_img_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='upper_snake',
            field=models.BooleanField(default=True),
        ),
    ]
