# Generated by Django 5.2 on 2025-07-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_composition_upper_snake'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='set_phase',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
